export const expenseCategories = [
  { label: "Housing", value: "housing" },
  { label: "Transportation", value: "transportation" },
  { label: "Food", value: "food" },
  { label: "Healthcare", value: "healthcare" },
  { label: "Utilities", value: "utilities" },
  { label: "Personal Care", value: "personal_care" },
  { label: "Entertainment", value: "entertainment" },
  { label: "Education", value: "education" },
  { label: "Debt Payments", value: "debt_payments" },
  { label: "Savings/Investments", value: "savings_investments" },
  { label: "Insurance", value: "insurance" },
  { label: "Taxes", value: "taxes" },
  { label: "Clothing", value: "clothing" },
  { label: "Travel", value: "travel" },
  { label: "Gifts/Donations", value: "gifts_donations" },
  { label: "Childcare", value: "childcare" },
  { label: "Home Supplies", value: "home_supplies" },
  { label: "Pets", value: "pets" },
  { label: "Miscellaneous", value: "miscellaneous" },
];
